### ISSUE TITLE
Snapping with Keyboard bug

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#5] opened 2023-06-14 18:31 UTC
After using the game controller for the first time, snapping with keyboard does not work anymore. Not matter which key I set for snapping (1st and 2nd key). But snapping with game controller still works. Like to play with keyboard...

**Comment by revvv** [comment] 2023-06-15 09:05
Please describe your problem more precisely. Which OS/Gamepad? gdash.log/console output?
Does snap work again after unplugging the controller and restarting GDash?

My guess: Mac has default keyboard shortcuts CTRL+CursorLeft/CTRL+CursorRight to switch desktops.
Just configure different snap key. L_ALT for example.

**Comment by cwscws** [comment] 2023-06-15 11:19
MacOS Ventura, M1 iMac
As soon as a controller is used, the snapping keys do not work again. No matter if a different snap key is defined, no matter if there is a second snap key defined. Snapping via keyboard simply does not work anymore. Not if the controller is detached or the program restarted. But up, down, left, right still works, only snapping not anymore. The controller does work on the other side, even snapping.

**Comment by cwscws** [comment] 2023-06-15 15:45
Controller is a PS4 controller connected via Bluetooth.

Keyboard is the standard iMac keyboard also connected via Bluetooth.

**Comment by cwscws** [comment] 2023-06-15 15:51
Found something interesting: When using GTK+ the snapping keys from the keyboard are accepted and working as normal. As soon as switching to OpenGL it does not work anymore!

**Comment by revvv** [comment] 2023-06-15 17:01
I can confirm that the snap keyboard mapping cannot be reconfigured on the Mac when using OpenGL.
The snap key is always the L_CTRL and works for CursorUp/CursorDown, but CTRL+CursorLeft/CTRL+CursorRight is a Mac hotkey (which can be reconfigured).

It has nothing to do with a game controller, right? So the task is to find out, why the mapping is ignored on Mac with OpenGL.

**Comment by cwscws** [comment] 2023-06-15 17:21
Yes, I know that it's a hotkey - so I do not want to reconfigure it. As in GTK+ the snap keyboard mapping works, there should be certainly a way that it works with OpenGL, too. I find it weird that it behaves that way but I think it has something to do with controller mapping. But as my controller is turned off and not connected it can't be something with the controller itself.

**Comment by revvv** [comment] 2023-06-16 12:05
Ok, this does occur also on Windows (and probably Linux).
Test case: Remove `gdash.ini`. Then define a new snap key, switch to OpenGL or SDL. Now the default key seems to be active again.

The solution: There are two mappings one for GTK and one for OpenGL/SDL.
To configure the mapping for OpenGL/SDL you have to press key 'K' and redefine the key.

IMHO this feature was done by intention. @cwscws Can we close the issue?

**Closed** 2023-06-30 14:38 UTC

**Comment by revvv** [comment] 2023-06-30 14:40
This fixes also this bug:
Press K, close dialog, press O to change engine GTK <-> SDL, press K =>
Messed up key codes!!!

Quite nasty to fix: I still don't know why a gameinputhandler in Setting array does not work...
