### ISSUE TITLE
Mac: Key stuck with keyboard input

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#6] opened 2023-06-16 19:09 UTC
Sometimes Rockford is stuck in one direction as long as the same direction is pressed again, then the stuck key is released and normal gameplay could be continued.

**Comment by revvv** [comment] 2023-06-17 08:14
I noticed that, too. Very rarely. Maybe more often in OpenGL mode.
Maybe this is a SDL feature. Once I know how to reproduce more reliable I'll add this [workaround](https://stackoverflow.com/questions/59725849/sdl-keyup-triggered-when-key-is-still-down).

**Comment by cwscws** [comment] 2023-06-17 08:56
Sounds good. Let's try that.

**Comment by revvv** [comment] 2023-06-20 09:40
Please try the [pre-release](https://github.com/revvv/gdash-export-CrLi/releases/tag/1.5.1). If it doesn't help maybe you could describe a test case to reliably reproduce it. (OS/Cave/etc)

**Comment by cwscws** [comment] 2023-06-20 17:57
No clear result here - first I thought that the key stuck is gone but in a test cave game Rockford suddenly continued running upwards even I stopped pressing up. Happened only once for the time but I'll have to test this more thorougly.

**Comment by cwscws** [comment] 2023-06-20 21:09
Tested it for some time but unfortunately the problem still occurs. The side effect of this fix is the you can not scroll through the game list by just keep pressing up or down, you have to single press the cursor key for each line.

**Comment by revvv** [comment] 2023-06-21 08:29
Ok, I'll remove the patch. I think this is a Mac-only issue? Could you give me a test case to reproduce it?
I saw it once or twice, but it's hard to reproduce on my two Macs (Catalina/Big Sur).

**Comment by cwscws** [comment] 2023-06-21 12:56
I can’t remember that this key stuck problem was an issue with the original release back in 2014 - I clearly remembered that cirix told me exactly how to compile it on my Mac I had back then and after it worked I also remember that I set it to OpenGL as scrolling and appearance was much better. But I really can’t remember that I ever had these key stuck problem. And I played it a lot back then - I would certainly remember such thing. 

So something must have changed. Maybe the whole layer under the program itself is the cause. I still think it has something to do with SDL. I read about a lot of similar problems when searching via google, and it doesn’t seem to be related to MacOS only.

it’s hard to reproduce as it seems to be random. I tried short keypresses or long ones and it does not happen in a regular periods of time. Sometimes it happens seldom, maybe all 2 or 3 caves once, sometimes it happens several times in a row and then not anymore for some time. I must observe it if maybe this happens when a lot os going on? Hmmm. There must be some kind of trigger. Maybe it has also something to do with Bluetooth as my iMac has a Bluetooth keyboard? But my old iMac also had a Bluetooth keyboard and no keystucks as far as I can remember. But the result of the bug is always the same: it is stuck in one direction and it only stops if you press exactly that direction once again and the stuck is gone.

As you also experienced this, it couldn’t be a coincidence. It would be interesting if it also happens on Windows and Linux.

**Comment by revvv** [comment] 2023-06-21 13:04
I suspect that `SDL_PollEvent()` omits events. Probably more often if fine scrolling and higher scaling factors are used.

**Comment by revvv** [comment] 2023-06-21 13:10
I suspect my changes in `joystick.cpp` caused this. I'll do a rollback and release a new beta.

**Comment by cwscws** [comment] 2023-06-21 16:18
Tested both new version 1.5.2 and 1.5.3
1.5.2 had the key stuck right in the first game and the first cave I played. So I immediately stopped further testing of 1.5.2

1.5.3 (preferred as Joystick support still in) worked a long period of time. Played several caves and also in editor a test cave game and no key stucks. Of course, could be a coincidence - but it looks promising and I'll continue testing.

I only had a complete program freeze in test cave game. Had to force quit the program.

**Comment by cwscws** [comment] 2023-06-21 16:23
Just played Boulder Dash 1 Cave M in Test Cave mode and I got a key stuck once. It seems random, totally random. 
But I'll continue testing - maybe it occurs less often with that fix. Lets see...

**Comment by revvv** [comment] 2023-06-21 16:59
Please always specify test case:
OS
Engine: GTK/SDL/OpenGL
Scaling factor
Cave
Joystick(s) connected or not

**Comment by revvv** [comment] 2023-06-21 17:09
> What do you think of that? [visualboyadvance-m/visualboyadvance-m#142](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/142)

Description sounds identical, but patch looks much like the focus lost bug, which I also found googling for "SDL stuck key".

**Comment by revvv** [comment] 2023-06-21 19:05
Could reproduce it 4x times:
Mac OS (Big Sur), OpenGL, Scaling factor: 3/4, BD1-M, no joystick connected

**Comment by cwscws** [comment] 2023-06-22 13:00
Key stuck also happens with the SDL graphics engine!

With GTK+ I didn't experience this yet but I'll continue testing.

I wonder if there is some place in the internet where to find professional care takers for such problems? Maybe it's something simple and we just do not know it?

**Comment by revvv** [comment] 2023-06-22 13:50
My guess is that in the event loop happens too much: https://stackoverflow.com/questions/35780073/sdl-pollevent-skips-events

In theory this bug can also happen on Windows and Linux. I tried to add some sleeps in the event loop on Windows, but never saw the bug occur. So IMHO there is something on the Mac SDL implementation.

I also compiled with -O3 on Mac, but this didn't help... I guess I should also compile the libs (at least SDL) with -O3, but don't how right now.

As the link suggests, we could optimize the event loop in [sdlmainwindow.cpp](https://github.com/revvv/gdash-export-CrLi/blob/a6f101a03220005b6660dfc1cb352f9cd9c8f4a2/src/sdl/sdlmainwindow.cpp#L166)

**Comment by cwscws** [comment] 2023-06-22 14:51
Everthing should be tried to improve the experience. Sometimes it happens not very often but it's a bad feeling as you never know when it happens...

**Comment by czirkoszoltan** [comment] 2023-06-22 17:40
Hey!

I wouldn't think that the main loop is slow, it runs in fullscreen etc. with a few % of cpu or even less. I cared a lot about speed and optimizations back then. And how the main loop with SDL_PollEvent is used follows the guidelines of SDL (https://wiki.libsdl.org/SDL2/SDL_PollEvent - a more authoritative source than a random SO question).

1.

There are two modes the game can run in.
- When timing is done by an SDL timer, and between the time ticks happening each 40ms or 20ms, it's spending its time waiting for events; that's the SDL_WaitEvent(NULL); line in sdlmainwindow.cpp:
```
            /* we must wait the next event here so we do not eat cpu.
             * but events are generated regurarly by the timer. */
            SDL_WaitEvent(NULL);
```
- When timing is done by the graphics card, being synchronized to the display itself:
```
            /* always flip, because we need the time it waits! */
            the_app.screen->do_the_flip();
```

This is a blind guess, but maybe the latter one is the problem.

We can check the mode by seeing what the output of this debug line was:
```
        gd_debug("red:%d green:%d blue:%d double_buffer:%d swap_control:%d", red, green, blue, double_buffer, swap_control);
```

If both double_buffer and swap_control are non-zero values, it's timed by the graphics card.



2.

I wonder if this is really caused by lost events. We should log the key presses / releases for that, like this in sdlmainwindow.cpp:

```
                case SDL_KEYDOWN:
                    gd_debug("keydown %s", ev.key.keysym.sym);  // new line to be added

...

                case SDL_KEYUP:
                    gd_debug("keyup %s", ev.key.keysym.sym);  // new line to be added
```

I'm keen to know here whether the keyup event is really missing when the problem happens. It will just print a lot of numbers, but experimenting with this a little, it will be easy to see which number represents which key.

**Comment by revvv** [comment] 2023-06-22 17:53
Thanks for the hints! I‘ll try…
I noticed that removing SDL_WaitEvent() freezes everything on Mac, but not on Windows… so we know which branch was entered.

**Comment by revvv** [comment] 2023-06-23 08:33
My Mac says:

    red:8 green:8 blue:8 double_buffer:1 swap_control:0

And there is no event missing, but I could not see the terminal window, so my guess the last keyup event came after focus lost.
I could not reproduce it with a smaller GDash window to confirm that. I keep on testing...

**Comment by revvv** [comment] 2023-06-23 08:45
Yes, looks like the missing event comes after focus lost:

    M:keydown 1073741904
    M:keydown 1073741903
    M:keyup 1073741903
    M:keyup 1073741904
    M:keydown 1073741903
    M:keydown 1073741904
    M:keyup 1073741903
    M:keyup 1073741904
    M:keydown 1073741903
    M:keydown 1073741904
    M:keyup 1073741903

    # stuck key!
    # now switch to terminal window

    M:keyup 1073741904
    M:red:8 green:8 blue:8 double_buffer:1 swap_control:0

**Comment by revvv** [comment] 2023-06-23 12:07
I have built an experimental release that does not call `g_main_context_iteration()` in `sdlmainwindow.cpp` for OpenGL:
https://github.com/revvv/gdash-export-CrLi/releases/download/1.5.4/gdash-export-1.5.4.1-mac-x86_64.dmg

Maybe that's a bad idea, but I have no other ideas any more... and I could not reproduce the bug... although this might be wrong in a few seconds ;-)

**Comment by cwscws** [comment] 2023-06-23 13:21
I played this for about half an hour in regular game (Boulder Dash 1 and Alchemist Dig 5) and several test caves from several games and the key stuck did not occur in OpenGL until now. It looks very very promising! I'll continue testing...

Can you mark the code in the source so that it can be inspected or reverted later if needed?

**Comment by revvv** [comment] 2023-06-23 13:31
Great..., but wait and see...
I haven't checked in the patch, it's available as download in the release area.
Once I check it in there will be a comment explaining the magic...

**Comment by czirkoszoltan** [comment] 2023-06-23 16:03
The problem with this would be that it breaks the game in the editor. In that scenario, two windows are open, one is GTK (for the editor) and the other one is SDL (for the testing). Both need to handle events, otherwise the operating system will think that the application is broken. And then, depending on the operating system (Win, Linux, MacOS) various things can happen, 1) nothing, 2) a window popping up saying that the application is broken, 3) the application just freezing etc. So generally you cannot remove those lines.

However, I recommend you continue with testing with those lines removed. If you are 100% sure that the stuck key problem does not happen anymore, then I can change how the editor works. Given that the editor always uses GTK for the edit window, it makes sense to use GTK for the game test window as well. After all, the fancy settings like fine scrolling etc. are only important for game plays, and not for the editor. If so, those lines will become removable, as it won't be possible anymore that both GTK and SDL windows are open at the same time.

So please continue testing so we can be 100% sure. I'm not using a Mac, so unfortunately I cannot do it.

**Comment by cwscws** [comment] 2023-06-23 16:29
Until now I have not seen a negative effect in editor white testing a cave. I didn’t get any error message yet. Sure, both windows are on the screen, the test cave window in front, the editor in back. But as far as I understand your concerns, both windows can’t be used at the same time anyway - you have to close the test cave window if you want to edit something. Or can I edit something and it immediately appears in the test cave window when open? Maybe I understood something wrong. Or it’s only with SDL (which I never use).

I have nothing against it that the test cave in the editor also runs in GTK but the new scaling factors beginning with 5 are not optimized yet and slowdowns are horrible with GTK. OpenGL is the only option for now for fluid game play with scaling factors larger than 4.

My initial idea was to add a preference option for the editor like „Use OpenGL for Test Cave“ or similar. So the editor and test cave would use GTK by default but if somebody would like to also have OpenGL for Test Cave he would be able to because of the editor preferences option…

Nevertheless I’ll continue testing. Let’s see if it occurs or it’s really fixed.

**Comment by cwscws** [comment] 2023-06-23 18:28
Started another game session for about 20 minutes and tried a lot in the different graphics settings, played around with the editor a bit, loaded different game, saved one to test if this works, and played several games with OpenGL and SDL and GTK in scale factor 4 and 5. Until now I didn't experience a key stuck. Will continue tomorrow.

**Comment by czirkoszoltan** [comment] 2023-06-24 05:25
I have created a commit to use GTK in editor cave tests. It makes it possible to remove those lines.
https://bitbucket.org/czirkoszoltan/gdash/commits/f980da7f4318f5296424720416911876bdb8d6bf

**Comment by cwscws** [comment] 2023-06-24 06:16
Switchable GTK/SDL/OpenGL?

**Comment by czirkoszoltan** [comment] 2023-06-24 07:01
No, because that would not allow removing those lines communicating with GTK. The whole idea is to avoid running GTK and SDL in parallel.

**Comment by cwscws** [comment] 2023-06-24 07:40
GTK scaling larger than 4 slows down cave test unplayable. Is there a solution for that dilemma?

**Comment by czirkoszoltan** [comment] 2023-06-24 07:47
Use it on a lower setting.
Apparently the Mac port of GTK is quite buggy and unoptimized.

**Comment by cwscws** [comment] 2023-06-24 17:08
I tested again two times today, at least 30 Minutes for each test. Procedure same as yesterday. I experienced no key stuck anymore. For me it seems that this issue has been fixed. At least it looks that way for now.

**Comment by revvv** [comment] 2023-06-26 08:26
> I have created a commit to use GTK in editor cave tests. It makes it possible to remove those lines. https://bitbucket.org/czirkoszoltan/gdash/commits/f980da7f4318f5296424720416911876bdb8d6bf

Thanks, and sorry, but my fork uses even OpenGL for test games. Previously only GTK/SDL was possible. (See #8)
To fix the stuck key issue which is Mac-only, I'm going to add my patch only for Mac (ifdef). It seems not to harm the Windows version, but so it's lees risky. And I don't have to test the Linux version ;-)

**Closed** 2023-06-26 11:20 UTC
