### ISSUE TITLE
GTK crash on MacOS at sorting elements in the Objects window

### ISSUE THREAD

**Issue by cwscws** [revvv/gdash-export-CrLi#15] opened 2023-07-14 10:49 UTC
GTK (and so GDash) crashes when sorting elements in the window in a specific way. 

Most times when drag-and-drop an element from above to below or sorting in general.

Seems to affect MacOS only.

**Comment by revvv** [comment] 2023-07-14 11:37
I can confirm that on my Mac: Edit cave -> Object list -> Drag first element and drop it as last element => Crash

gdash -v output:

    D:GTask init_compose_table_async (source object: 0x0, source tag: 0x10a467600) finalized without ever returning (using g_task_return_*()). This potentially indicates a bug in the program.
    W:corrupted double-linked list detected
    (gdash:12896): GLib-WARNING **: 10:25:22.118: corrupted double-linked list detected
    M:configure_size: window w/o particle effects
    zsh: segmentation fault  src/gdash

Note that the log with `init_compose_table_async` only appeared in the first test, very strange.
Google for that term shows an interesting bug fix:
https://gitlab.gnome.org/GNOME/gtk/-/commit/6402137bbfc4a0761fb103e2c26d18774756913a

This was fixed in GTK 3.24.38, while GDash Mac uses 3.24.36.
I'll have to test if the new version fixes our issue, but we cannot upgrade easily to latest GTK version, because of this bug #2

If this doesn't fix it, there is another suspicious warning, that always occured:

    corrupted double-linked list detected

**Comment by revvv** [comment] 2023-07-14 12:28
Result: GTK 3.24.38 does not fix our problem.

**Comment by cwscws** [comment] 2023-07-15 13:48
Seems to happen on the Windows version, too.

Tried the same on Windows 11 ARM and also crashes there.

**Comment by revvv** [comment] 2023-07-15 14:25
You tested on iMac Parallels Desktop.

I tested on my Windows 10: It crashes rarely, and very rarely while debugging:

    #27 0x00007ff62b46fd23 in gd_cave_editor_run (caveset=caveset@entry=0x5fa3d0) at editor/editor.cpp:3795

but this stacktrace doesn't help much... not sure what's going on.

**Comment by cwscws** [comment] 2023-07-15 16:39
It doesn’t happen on Windows 11 ARM as often as on MacOS - but when it does the crash is the same.

**Comment by revvv** [comment] 2023-07-16 15:14
My guess is that there is a synchronization problem in GTK. Looking at the logs above IMHO it seems that GTK calls a drag and drop handler that interferes with our callback.

I can reduce code from `object_list_row_delete` so that it does not occur, but this then the view is not up to date etc

**Comment by cwscws** [comment] 2023-07-16 15:47
But it’s weird that it crashes more on MacOS than on Windows.

**Comment by revvv** [comment] 2023-07-17 09:04
I added a workaround: The `row-delete` handler interferes somehow with `gtk_drag_drop_finished()`. (See Mac error report)
So I just moved the code to the `drag-end` handler, which seems to work.

**Closed** 2023-07-21 11:43 UTC
